# Generated by Django 4.2 on 2023-04-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.ImageField(default='bhjhjk', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
